USE oepnacrt;
SELECT * FROM oc_order WHERE order_id=1 ORDER BY date_added DESC LIMIT 1;
SELECT COUNT(*) FROM oc_order_product op LEFT JOIN oc_order o ON op.order_id=o.order_id WHERE o.order_id = 1;
START TRANSACTION; CALL sp_place_order(5); ROLLBACK; SELECT COUNT(*) FROM oc_order WHERE customer_id=5 AND date_added > NOW() - INTERVAL 1 MINUTE;
SELECT * FROM oc_order WHERE order_id=1001;
SELECT payment_method FROM oc_order WHERE order_id=1;
INSERT INTO oc_order (order_id, customer_id) VALUES (1, 1);
SELECT SUM(quantity) FROM oc_cart WHERE customer_id=5; SELECT SUM(quantity) FROM oc_order_product WHERE order_id=1001;
SELECT order_status_id FROM oc_order WHERE order_id=1002;
SELECT order_status_id FROM oc_order WHERE order_id=1001;
SELECT * FROM oc_order_total WHERE order_id=2;
SELECT order_id,date_added FROM oc_order WHERE customer_id=1 ORDER BY date_added DESC;
UPDATE oc_order SET order_status_id=3 WHERE order_id=2; 
SELECT order_status_id FROM oc_order WHERE order_id=2;
SELECT COUNT(*) FROM oc_order_total t LEFT JOIN oc_order o ON t.order_id=o.order_id WHERE o.order_id IS NULL;
INSERT INTO oc_order (customer_id,total) VALUES (5,NULL);
SELECT total FROM oc_order WHERE order_id=1004;
SELECT email FROM oc_customer WHERE customer_id=5;
DELETE FROM oc_order WHERE order_id=1001;
DELETE FROM oc_order WHERE order_id=3; 
SELECT COUNT(*) FROM oc_order_product WHERE order_id=3;
INSERT INTO oc_customer (email,firstname) VALUES ('demo@demo.com','Muhammed');